[tool.poetry]
name = "modular-calc-jfy"
version = "0.1.0"
description = ""
authors = ["Jan Meineke <jan.meineke@mailbox.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
PyQt6 = "^6.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
